services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: football-predictor-frontend:current
    ports:
      - "3000:80"
    networks:
      - football-predictor_default
    restart: unless-stopped

networks:
  football-predictor_default:
    external: true
