import { GlossaryEntry } from './glossaryTypes';
import { GLOSSARY_PLAIN_LANGUAGE } from './glossaryPlainLanguage';

const entries: GlossaryEntry[] = [
  {
    id: 'decimal-odds',
    term: 'Quota decimale',
    aliases: ['quota'],
    category: 'Quote e probabilità',
    simpleDefinition: 'Indica quanto viene restituito complessivamente per ogni euro puntato, includendo la puntata iniziale.',
    technicalDefinition: 'È il moltiplicatore lordo applicato allo stake quando la selezione vince. Il profitto netto è la restituzione totale meno lo stake.',
    formula: 'Restituzione = stake × quota; profitto = stake × (quota − 1)',
    example: 'Con quota 2,10 e puntata di 10 €, la restituzione è 21 € e il profitto netto è 11 €.',
    highValue: 'Una quota alta implica un evento ritenuto meno probabile dal mercato e una restituzione potenziale maggiore.',
    lowValue: 'Una quota bassa implica un evento ritenuto più probabile e una restituzione potenziale più contenuta.',
    positiveMeaning: 'È favorevole solo quando remunera adeguatamente la probabilità reale stimata e il rischio assunto.',
    negativeMeaning: 'È sfavorevole quando sottopaga il rischio, anche se la selezione appare molto probabile.',
    interpretation: 'Confrontala sempre con la probabilità stimata dal modello, non giudicarla da sola.',
    caution: 'Una quota alta non è automaticamente conveniente e una quota bassa non è automaticamente sicura.',
    relatedTerms: ['implied-probability', 'expected-value', 'stake'],
  },
  {
    id: 'implied-probability',
    term: 'Probabilità implicita',
    category: 'Quote e probabilità',
    simpleDefinition: 'È la probabilità suggerita dalla quota del bookmaker prima di correggere il suo margine.',
    technicalDefinition: 'Si ottiene invertendo la quota decimale. Nei mercati con più esiti, la somma supera spesso il 100% a causa dell’overround.',
    formula: 'Probabilità implicita (%) = (1 ÷ quota decimale) × 100',
    example: 'Una quota 2,00 corrisponde al 50%; una quota 1,50 corrisponde a circa il 66,7%.',
    highValue: 'Un valore alto significa che il mercato considera l’esito più probabile e offre una quota più bassa.',
    lowValue: 'Un valore basso significa che il mercato considera l’esito meno probabile e offre una quota più alta.',
    positiveMeaning: 'È utile come riferimento quando viene confrontata con una probabilità modello ben calibrata.',
    negativeMeaning: 'Può essere fuorviante se viene trattata come probabilità pura senza rimuovere il margine bookmaker.',
    interpretation: 'Il value emerge quando la probabilità modello supera in modo credibile quella implicita corretta.',
    caution: 'Non sommare o confrontare probabilità implicite di mercati diversi senza controllare margine e struttura.',
    relatedTerms: ['decimal-odds', 'overround', 'no-vig-odds', 'model-probability'],
  },
  {
    id: 'model-probability',
    term: 'Probabilità stimata dal modello',
    category: 'Quote e probabilità',
    simpleDefinition: 'È la stima dell’app sulla possibilità che una selezione si verifichi in quella partita.',
    technicalDefinition: 'Deriva dai modelli statistici e dai dati disponibili; non è una certezza e deve essere valutata insieme a calibrazione, campione e qualità dati.',
    formula: 'Stima modello = funzione(dati storici, parametri, contesto e mercato)',
    example: 'Se il modello stima Over 2.5 al 56% e la quota implica il 48%, esiste un possibile vantaggio.',
    highValue: 'Un valore alto indica che il modello ritiene l’esito frequente, non che l’esito sia garantito.',
    lowValue: 'Un valore basso indica che il modello ritiene l’esito raro, ma non impossibile.',
    positiveMeaning: 'È informativa quando il modello è calibrato e il campione sottostante è sufficiente.',
    negativeMeaning: 'È debole quando dati mancanti, cambi di formazione o campioni piccoli rendono instabile la stima.',
    interpretation: 'Leggila come frequenza attesa su molti casi simili, non come promessa sulla singola partita.',
    caution: 'Piccole differenze rispetto al bookmaker possono essere rumore statistico o effetto del margine.',
    relatedTerms: ['calibration', 'data-quality', 'statistical-sample', 'edge'],
  },
  {
    id: 'vig',
    term: 'Vig',
    aliases: ['vigorish'],
    category: 'Quote e probabilità',
    simpleDefinition: 'È un altro nome per la commissione o margine incorporato dal bookmaker nelle quote.',
    technicalDefinition: 'Rappresenta il costo teorico del mercato per lo scommettitore e viene spesso stimato tramite l’overround degli esiti mutuamente esclusivi.',
    formula: 'Vig grezzo = somma(1 ÷ quota di ogni esito) − 1',
    example: 'Quote che producono probabilità totali del 105% contengono un vig grezzo del 5%.',
    highValue: 'Un vig alto riduce il rendimento atteso e rende più difficile trovare value.',
    lowValue: 'Un vig basso rende il confronto tra quota e probabilità modello più favorevole e leggibile.',
    positiveMeaning: 'La sua rimozione permette un confronto più corretto con la stima del modello.',
    negativeMeaning: 'Ignorarlo può far sembrare positivo un vantaggio che in realtà copre solo il margine.',
    interpretation: 'Trattalo come costo del prezzo e non come informazione sulla forza sportiva delle squadre.',
    caution: 'Metodi diversi di rimozione del vig possono produrre probabilità no-vig leggermente differenti.',
    relatedTerms: ['overround', 'edge'],
  },
  {
    id: 'overround',
    term: 'Overround',
    category: 'Quote e probabilità',
    simpleDefinition: 'È la parte oltre il 100% ottenuta sommando le probabilità implicite di tutti gli esiti.',
    technicalDefinition: 'Misura il margine lordo del book per un mercato completo, prima di qualsiasi modello sulla distribuzione del margine.',
    formula: 'Overround = somma probabilità implicite − 100%',
    example: 'Probabilità implicite 48%, 30% e 28% sommano 106%: overround pari a 6%.',
    highValue: 'Un overround alto segnala prezzi meno competitivi e maggior costo implicito.',
    lowValue: 'Un overround vicino a zero segnala quote più efficienti, pur non garantendo value.',
    positiveMeaning: 'È utile per confrontare la qualità di prezzo tra mercati equivalenti.',
    negativeMeaning: 'Diventa negativo per l’utente quando erode un edge già piccolo.',
    interpretation: 'Calcolalo sul mercato completo e poi normalizza gli esiti per ottenere probabilità no-vig.',
    caution: 'Non è una stima esatta del profitto futuro del bookmaker né della probabilità reale.',
    relatedTerms: ['implied-probability', 'no-vig-odds'],
  },
  {
    id: 'no-vig-odds',
    term: 'Quota senza vig',
    aliases: ['quota no-vig'],
    category: 'Quote e probabilità',
    simpleDefinition: 'È una quota teorica ricavata rimuovendo il margine del bookmaker dal mercato.',
    technicalDefinition: 'Si normalizzano le probabilità implicite affinché sommino al 100% e poi si convertono nuovamente in quote decimali.',
    formula: 'p no-vig = p implicita ÷ somma p implicite; quota no-vig = 1 ÷ p no-vig',
    example: 'Se un esito pesa 52 su un totale di 105, la probabilità no-vig è 49,5%.',
    highValue: 'Una quota no-vig alta corrisponde a una probabilità neutrale più bassa.',
    lowValue: 'Una quota no-vig bassa corrisponde a una probabilità neutrale più alta.',
    positiveMeaning: 'Consente di misurare un edge più pulito rispetto al prezzo di mercato.',
    negativeMeaning: 'Può dare falsa precisione quando il mercato è poco liquido o il metodo di rimozione è inadeguato.',
    interpretation: 'Usala come benchmark teorico, mantenendo la quota Eurobet reale come prezzo eseguibile.',
    caution: 'Non è una quota realmente disponibile e non deve essere mostrata come offerta del bookmaker.',
    relatedTerms: ['vig', 'edge'],
  },
  {
    id: 'value-bet',
    term: 'Value bet',
    category: 'Value betting',
    simpleDefinition: 'È una scommessa la cui quota remunera più di quanto suggerisca la probabilità stimata.',
    technicalDefinition: 'Esiste valore teorico quando il prodotto tra probabilità stimata e quota decimale supera uno, dopo costi e controlli di affidabilità.',
    formula: 'Value teorico se probabilità modello × quota > 1',
    example: 'Con probabilità 55% e quota 2,00, il valore atteso lordo è circa +10%.',
    highValue: 'Un vantaggio stimato alto può essere interessante ma richiede controllo di dati, mercato e rischio modello.',
    lowValue: 'Un vantaggio minimo può non compensare margine, errore di stima e varianza.',
    positiveMeaning: 'È positivo quando persiste su un campione adeguato e con quote realmente disponibili.',
    negativeMeaning: 'È negativo quando deriva da dati scarsi, quota non eseguibile o modello non calibrato.',
    interpretation: 'Una value bet può perdere; il concetto riguarda il rendimento medio di molte decisioni simili.',
    caution: 'Non confondere value con probabilità di vittoria e non usare quote sintetiche come prezzi disponibili.',
    relatedTerms: ['expected-value', 'edge', 'statistical-sample'],
  },
  {
    id: 'expected-value',
    term: 'Valore atteso (EV)',
    acronym: 'EV',
    category: 'Value betting',
    simpleDefinition: 'Stima il profitto o la perdita media teorica per unità puntata ripetendo molte volte decisioni simili.',
    technicalDefinition: 'Per una scommessa binaria con quota decimale, confronta il ritorno ponderato dalla probabilità stimata con la puntata iniziale.',
    formula: 'EV = (probabilità modello × quota decimale) − 1',
    example: 'Probabilità 55% e quota 2,00 producono EV 0,10, cioè +10% teorico per unità puntata.',
    highValue: 'Un EV alto indica maggiore rendimento teorico, ma può anche segnalare quota anomala o stima instabile.',
    lowValue: 'Un EV vicino a zero offre poco margine contro errori di modello e variazioni di quota.',
    positiveMeaning: 'EV positivo indica convenienza teorica se probabilità e quota sono affidabili.',
    negativeMeaning: 'EV negativo indica che il prezzo non remunera abbastanza il rischio stimato.',
    interpretation: 'Valutalo con affidabilità, campione, fonte quota e rischio; non come previsione del singolo esito.',
    caution: 'EV elevato su poche giocate o quote non disponibili non prova una strategia redditizia.',
    relatedTerms: ['value-bet', 'edge', 'roi', 'calibration'],
  },
  {
    id: 'edge',
    term: 'Edge',
    category: 'Value betting',
    simpleDefinition: 'È la differenza tra la probabilità stimata dal modello e quella attribuita dal mercato.',
    technicalDefinition: 'Può essere calcolato contro probabilità implicita grezza o, preferibilmente, contro probabilità no-vig del mercato.',
    formula: 'Edge = probabilità modello − probabilità di mercato',
    example: 'Modello 56% e mercato no-vig 51% producono un edge di 5 punti percentuali.',
    highValue: 'Un edge alto segnala forte disaccordo con il mercato e richiede una verifica più rigorosa dei dati.',
    lowValue: 'Un edge basso può essere insufficiente a coprire errore modello, margine e movimento quota.',
    positiveMeaning: 'Edge positivo indica che il modello assegna maggiore probabilità rispetto al mercato.',
    negativeMeaning: 'Edge negativo indica che il mercato è più ottimista del modello sulla selezione.',
    interpretation: 'Leggilo in punti percentuali e insieme a quota, EV, calibrazione e qualità dati.',
    caution: 'Un edge positivo non garantisce profitto e può sparire quando la quota cambia.',
    relatedTerms: ['model-probability', 'no-vig-odds', 'expected-value'],
  },
  {
    id: 'bankroll',
    term: 'Bankroll',
    category: 'Gestione del bankroll',
    simpleDefinition: 'È il capitale separato e destinato esclusivamente alle scommesse.',
    technicalDefinition: 'Costituisce la base per calcolare stake, esposizione, rendimento e limiti di rischio senza coinvolgere denaro necessario ad altre spese.',
    example: 'Con bankroll di 1.000 €, uno stake dell’1% corrisponde a 10 €.',
    highValue: 'Un bankroll alto consente importi maggiori a pari percentuale, ma non rende migliori le decisioni.',
    lowValue: 'Un bankroll basso richiede stake assoluti contenuti e particolare attenzione ai limiti minimi.',
    positiveMeaning: 'È sano quando è separato, aggiornato e coerente con la tolleranza alle perdite.',
    negativeMeaning: 'È rischioso quando include denaro necessario o viene aumentato per recuperare perdite.',
    interpretation: 'Ragiona sempre in percentuale del bankroll corrente, non soltanto in euro.',
    caution: 'Non considerare il bankroll una garanzia di recupero: può diminuire anche con una strategia valida.',
    relatedTerms: ['stake', 'exposure', 'fractional-kelly'],
  },
  {
    id: 'stake',
    term: 'Stake',
    category: 'Gestione del bankroll',
    simpleDefinition: 'È l’importo effettivamente puntato su una singola selezione.',
    technicalDefinition: 'Viene espresso in euro o come percentuale del bankroll e determina l’impatto economico dell’esito.',
    formula: 'Stake in euro = bankroll × percentuale stake',
    example: 'Bankroll 800 € e stake 1,5% corrispondono a una puntata di 12 €.',
    highValue: 'Uno stake alto aumenta rendimento potenziale, perdita possibile e volatilità del bankroll.',
    lowValue: 'Uno stake basso limita il rischio ma può rendere trascurabile il rendimento assoluto.',
    positiveMeaning: 'È positivo quando è proporzionato a edge, affidabilità e rischio complessivo.',
    negativeMeaning: 'È negativo quando nasce da impulso, recupero perdite o eccessiva fiducia.',
    interpretation: 'Usa lo stake suggerito come limite prudente, non come obbligo di puntata.',
    caution: 'La percentuale non è la probabilità di vincita e va ridotta quando le stime sono incerte.',
    relatedTerms: ['bankroll', 'exposure', 'kelly-criterion'],
  },
  {
    id: 'exposure',
    term: 'Esposizione',
    category: 'Rischio e stake',
    simpleDefinition: 'È la parte del bankroll impegnata in scommesse ancora pendenti.',
    technicalDefinition: 'Somma gli stake non regolati e misura quanto capitale è temporaneamente a rischio prima degli esiti.',
    formula: 'Esposizione = somma stake delle scommesse pendenti',
    example: 'Tre puntate pendenti da 10 €, 15 € e 20 € producono esposizione di 45 €.',
    highValue: 'Un’esposizione alta riduce liquidità disponibile e amplifica il rischio di risultati correlati.',
    lowValue: 'Un’esposizione bassa mantiene maggiore flessibilità e limita il drawdown simultaneo.',
    positiveMeaning: 'È gestibile quando resta entro il limite definito e le puntate non sono eccessivamente correlate.',
    negativeMeaning: 'È pericolosa quando concentra troppo capitale sulla stessa partita, lega o finestra temporale.',
    interpretation: 'Confrontala con bankroll disponibile e calendario delle scommesse pendenti.',
    caution: 'La semplice somma non misura perfettamente la correlazione tra selezioni.',
    relatedTerms: ['bankroll', 'stake', 'pending-bet'],
  },
  {
    id: 'kelly-criterion',
    term: 'Criterio di Kelly',
    aliases: ['Kelly Criterion'],
    category: 'Rischio e stake',
    simpleDefinition: 'È una formula che suggerisce quale quota del bankroll puntare in base a probabilità e prezzo.',
    technicalDefinition: 'Massimizza la crescita logaritmica attesa del capitale assumendo probabilità corrette e ripetibilità delle opportunità.',
    formula: 'Kelly = ((quota − 1) × p − (1 − p)) ÷ (quota − 1)',
    example: 'Quota 2,00 e probabilità 55% producono Kelly pieno del 10% del bankroll.',
    highValue: 'Un Kelly alto segnala grande edge stimato, ma è molto sensibile agli errori della probabilità.',
    lowValue: 'Un Kelly basso segnala un vantaggio piccolo o una quota poco remunerativa.',
    positiveMeaning: 'Un valore positivo indica stake teorico; Kelly zero o negativo suggerisce nessuna puntata.',
    negativeMeaning: 'Un valore negativo indica assenza di vantaggio secondo la stima inserita.',
    interpretation: 'L’app usa Kelly frazionale e limiti di esposizione per ridurre volatilità e rischio modello.',
    caution: 'Kelly pieno può essere aggressivo e dannoso quando la probabilità stimata è imprecisa.',
    relatedTerms: ['fractional-kelly', 'stake', 'edge'],
  },
  {
    id: 'fractional-kelly',
    term: 'Kelly frazionale',
    category: 'Rischio e stake',
    simpleDefinition: 'Applica soltanto una parte dello stake suggerito dal Kelly pieno.',
    technicalDefinition: 'Moltiplica la frazione Kelly teorica per un coefficiente prudente, riducendo crescita attesa ma anche volatilità e rischio di rovina.',
    formula: 'Kelly frazionale = Kelly pieno × frazione scelta',
    example: 'Kelly pieno 8% e Kelly a un quarto producono uno stake del 2%.',
    highValue: 'Una frazione alta si avvicina al Kelly pieno e aumenta sensibilmente la volatilità.',
    lowValue: 'Una frazione bassa è più prudente e tollera meglio errori di stima.',
    positiveMeaning: 'È utile per adattare il sizing a incertezza, qualità dati e tolleranza al rischio.',
    negativeMeaning: 'Resta rischioso se applicato a un edge falso o a quote non realmente disponibili.',
    interpretation: 'La percentuale risultante rappresenta quota del bankroll, non probabilità di vincita.',
    caution: 'Non aumentare la frazione dopo una perdita per tentare di recuperare.',
    relatedTerms: ['kelly-criterion', 'bankroll', 'exposure'],
  },
  {
    id: 'roi',
    term: 'Rendimento sull’investimento (ROI)',
    acronym: 'ROI',
    category: 'Gestione del bankroll',
    simpleDefinition: 'Misura quanto profitto netto è stato prodotto rispetto al totale puntato.',
    technicalDefinition: 'Rapporta il profitto netto alla somma degli stake regolati. Permette confronti tra periodi o strategie con volumi diversi, ma non descrive da solo rischio e affidabilità.',
    formula: 'ROI (%) = profitto netto ÷ totale puntato × 100',
    example: 'Con 1.000 € puntati e 80 € di profitto netto, il ROI è +8%.',
    highValue: 'Un ROI alto è favorevole solo se sostenuto da molte scommesse, quote reali e varianza controllata.',
    lowValue: 'Un ROI vicino allo zero indica pareggio; può essere normale su campioni brevi.',
    positiveMeaning: 'ROI positivo significa che i ritorni hanno superato gli stake complessivi.',
    negativeMeaning: 'ROI negativo significa che la strategia ha perso rispetto al capitale puntato.',
    interpretation: 'Leggilo sempre con numero di scommesse, volume, CLV, drawdown e intervallo temporale.',
    caution: 'Un ROI molto alto su poche scommesse può essere casuale e non dimostra una strategia affidabile.',
    relatedTerms: ['win-rate', 'statistical-sample', 'clv'],
  },
  {
    id: 'win-rate',
    term: 'Tasso di vittoria (win rate)',
    aliases: ['win rate'],
    category: 'Gestione del bankroll',
    simpleDefinition: 'È la percentuale di scommesse concluse che risultano vincenti.',
    technicalDefinition: 'Rapporta le vittorie alle decisioni risolte, di norma escludendo pendenti e void; non considera il livello delle quote.',
    formula: 'Win rate (%) = vinte ÷ (vinte + perse) × 100',
    example: '58 vinte e 42 perse su 100 decisioni producono win rate del 58%.',
    highValue: 'Un win rate alto può essere necessario con quote basse, ma non garantisce profitto.',
    lowValue: 'Un win rate basso può essere redditizio se le vincite arrivano a quote sufficientemente alte.',
    positiveMeaning: 'È positivo quando è coerente con la quota media necessaria al pareggio.',
    negativeMeaning: 'È negativo quando non raggiunge il break-even richiesto dai prezzi giocati.',
    interpretation: 'Confrontalo con quota media, ROI e profitto; da solo non misura la redditività.',
    caution: 'Escludere o includere void e pendenti in modo incoerente distorce il confronto.',
    relatedTerms: ['roi', 'decimal-odds'],
  },
  {
    id: 'pending-bet',
    term: 'Scommessa pendente',
    category: 'Gestione del bankroll',
    simpleDefinition: 'È una scommessa registrata il cui risultato non è ancora stato regolato.',
    technicalDefinition: 'Lo stake rimane esposto e non contribuisce ancora a vittorie, sconfitte o profitto realizzato.',
    example: 'Una partita di domani con stake 15 € resta pendente fino al risultato e alla disponibilità dei dati.',
    highValue: 'Molte pendenti aumentano esposizione, concentrazione temporale e capitale non disponibile.',
    lowValue: 'Poche pendenti mantengono maggiore liquidità, ma non sono di per sé un obiettivo.',
    positiveMeaning: 'È uno stato normale quando quota, selezione e stake sono registrati correttamente.',
    negativeMeaning: 'È problematico se rimane tale dopo la conclusione per dati mancanti o errore di regolazione.',
    interpretation: 'Considera lo stake pendente come capitale a rischio, non come profitto o perdita realizzati.',
    caution: 'Non duplicare la stessa giocata mentre risulta ancora pendente.',
    relatedTerms: ['exposure', 'void', 'stake'],
  },
  {
    id: 'void',
    term: 'Void',
    category: 'Gestione del bankroll',
    simpleDefinition: 'Indica una scommessa annullata, normalmente con restituzione dello stake.',
    technicalDefinition: 'La decisione viene regolata senza vittoria o perdita e dovrebbe avere profitto netto pari a zero.',
    example: 'Partita rinviata secondo le regole del mercato: la puntata di 10 € viene restituita.',
    highValue: 'Un numero alto di void può indicare problemi di mercato, dati o regole di regolazione.',
    lowValue: 'Pochi void sono normali e non incidono direttamente sul profitto.',
    positiveMeaning: 'Protegge lo stake quando l’evento non può essere valutato secondo le condizioni previste.',
    negativeMeaning: 'Può nascondere anomalie se viene usato per correggere manualmente esiti problematici.',
    interpretation: 'Mostralo separatamente da vinte, perse e pendenti.',
    caution: 'Le regole di void dipendono dal mercato e dal bookmaker; non assumerle uguali per tutti.',
    relatedTerms: ['pending-bet', 'win-rate'],
  },
  {
    id: 'confidence',
    term: 'Affidabilità (confidence)',
    aliases: ['confidence'],
    category: 'Rischio e stake',
    simpleDefinition: 'Riassume quanto il sistema considera solida una stima rispetto ai dati e ai controlli disponibili.',
    technicalDefinition: 'È una classificazione derivata da copertura, stabilità, campione e coerenza del modello; non rappresenta una probabilità aggiuntiva.',
    example: 'Affidabilità alta può indicare dati completi e stima stabile, pur senza garantire l’esito.',
    highValue: 'Alta significa condizioni informative migliori e minori segnali di fragilità.',
    lowValue: 'Bassa significa campione, dati o stabilità insufficienti per una decisione forte.',
    positiveMeaning: 'È positiva quando spiega chiaramente quali evidenze la sostengono.',
    negativeMeaning: 'È negativa quando viene letta come garanzia di vittoria o usata per ignorare il rischio.',
    interpretation: 'Usala per modulare prudenza e stake insieme alla probabilità stimata.',
    caution: 'Due selezioni con stessa confidence possono avere probabilità e quote molto diverse.',
    relatedTerms: ['data-quality', 'statistical-sample'],
  },
  {
    id: 'speculative',
    term: 'Speculative (speculativa)',
    aliases: ['speculative', 'speculativa'],
    category: 'Rischio e stake',
    simpleDefinition: 'Indica una selezione che può avere value teorico, ma non ha affidabilità sufficiente per essere una giocata operativa.',
    technicalDefinition: 'È uno stato diagnostico assegnato quando la selezione resta valutabile ma presenta confidence LOW, campione insufficiente o altri segnali di instabilità.',
    example: 'Una quota 5,40 con EV positivo ma campione storico mancante può essere mostrata come speculativa.',
    highValue: 'Può segnalare un’idea interessante da monitorare o verificare con nuovi dati.',
    lowValue: 'Non deve essere interpretata come consiglio principale né come autorizzazione automatica a puntare.',
    positiveMeaning: 'Mantiene visibile un possibile segnale senza confonderlo con una decisione sufficientemente affidabile.',
    negativeMeaning: 'Diventa rischiosa se viene scambiata per una bet operativa solo perché l’EV teorico è positivo.',
    interpretation: 'Le selezioni speculative sono escluse dal limite delle tre bet operative e dall’automazione.',
    caution: 'Value positivo e quota alta non compensano da soli campione nullo, dati deboli o incertezza elevata.',
    relatedTerms: ['confidence', 'value-bet', 'expected-value', 'statistical-sample'],
  },
  {
    id: 'european-handicap',
    term: 'Handicap europeo',
    category: 'Mercati di scommessa',
    simpleDefinition: 'Aggiunge o sottrae gol virtuali e mantiene tre possibili esiti: casa, pareggio, ospite.',
    technicalDefinition: 'Il punteggio viene corretto dalla linea intera prima di determinare un esito 1X2 a tre vie.',
    example: 'Casa -1: una vittoria reale di un gol produce pareggio handicap, non vittoria casa.',
    highValue: 'Una linea più severa richiede una vittoria più ampia e offre normalmente quota più alta.',
    lowValue: 'Una linea meno severa riduce il requisito e normalmente la quota.',
    positiveMeaning: 'Può offrire prezzo migliore quando il modello prevede ampio scarto.',
    negativeMeaning: 'È facile da interpretare male confondendo il pareggio handicap con rimborso.',
    interpretation: 'Applica prima l’handicap al risultato e poi valuta 1, X o 2.',
    caution: 'Non è equivalente all’Asian Handicap, che può prevedere push e mezze vincite.',
    relatedTerms: ['asian-handicap'],
  },
  {
    id: 'asian-handicap',
    term: 'Asian Handicap',
    category: 'Mercati di scommessa',
    simpleDefinition: 'Applica un vantaggio o svantaggio virtuale eliminando spesso il pareggio come perdita piena.',
    technicalDefinition: 'Linee intere possono produrre push; linee quarti dividono lo stake su due handicap adiacenti, generando mezze vincite o perdite.',
    example: 'Casa -0.25 divide la puntata tra 0 e -0.5: un pareggio produce mezza perdita.',
    highValue: 'Un handicap negativo più alto richiede una vittoria più larga e aumenta il rischio.',
    lowValue: 'Un handicap positivo protegge maggiormente la squadra scelta ma riduce la quota.',
    positiveMeaning: 'Consente di modellare lo scarto in modo più granulare rispetto al 1X2.',
    negativeMeaning: 'Può confondere senza una chiara spiegazione delle linee intere, mezze e quarti.',
    interpretation: 'Verifica sempre la linea esatta e come viene diviso lo stake.',
    caution: 'Non assumere che tutte le piattaforme mostrino o regolino le linee nello stesso formato.',
    relatedTerms: ['european-handicap', 'void', 'poisson-distribution'],
  },
  {
    id: 'lambda',
    term: 'Lambda (tasso di gol atteso)',
    acronym: 'λ',
    category: 'Modelli statistici',
    simpleDefinition: 'È il numero medio di gol che il modello attribuisce a una squadra per la partita.',
    technicalDefinition: 'È il parametro di intensità di una distribuzione di Poisson e combina forza offensiva, difesa avversaria e vantaggio campo.',
    formula: 'P(X = k) = e^(−λ) × λ^k ÷ k!',
    example: 'Lambda casa 1,70 significa media teorica di 1,70 gol su molte partite simili.',
    highValue: 'Lambda alto sposta probabilità verso più gol della squadra.',
    lowValue: 'Lambda basso concentra probabilità su zero o un gol.',
    positiveMeaning: 'È utile quando deriva da dati recenti, stabili e coerenti con il campionato.',
    negativeMeaning: 'È debole se viene interpretato come punteggio certo o stimato da campioni insufficienti.',
    interpretation: 'Nella UI di base viene mostrato come “gol attesi”; il termine tecnico resta nei dettagli.',
    caution: 'La Poisson semplice può sottostimare correlazioni e dispersione reale dei risultati.',
    relatedTerms: ['poisson-distribution', 'dixon-coles'],
  },
  {
    id: 'poisson-distribution',
    term: 'Distribuzione di Poisson',
    category: 'Modelli statistici',
    simpleDefinition: 'È un modello probabilistico usato per stimare quanti gol possono verificarsi in una partita.',
    technicalDefinition: 'Descrive il conteggio di eventi indipendenti in un intervallo dato un tasso medio lambda costante.',
    formula: 'P(X = k) = e^(−λ) × λ^k ÷ k!',
    example: 'Con lambda 1,5 si calcola la probabilità di 0, 1, 2 o più gol.',
    highValue: 'Lambda alto nella Poisson distribuisce più massa sui conteggi elevati.',
    lowValue: 'Lambda basso concentra la probabilità sui conteggi bassi.',
    positiveMeaning: 'È semplice, interpretabile e utile come base per mercati gol e risultati.',
    negativeMeaning: 'È limitata quando eventi non sono indipendenti o la varianza supera la media.',
    interpretation: 'Valuta la distribuzione completa, non soltanto il suo valore medio.',
    caution: 'Partite reali possono avere dipendenze tattiche e overdispersione non catturate.',
    relatedTerms: ['lambda', 'dixon-coles', 'negative-binomial'],
  },
  {
    id: 'dixon-coles',
    term: 'Modello Dixon-Coles',
    category: 'Modelli statistici',
    simpleDefinition: 'È un’estensione del modello Poisson pensata per stimare risultati delle partite di calcio.',
    technicalDefinition: 'Stima forze di attacco e difesa e corregge la dipendenza dei punteggi bassi, spesso pesando maggiormente le partite recenti.',
    example: 'Corregge probabilità di 0-0, 1-0, 0-1 e 1-1 rispetto a due Poisson indipendenti.',
    highValue: 'Non ha un singolo valore alto: parametri estremi richiedono controllo della stabilità del fit.',
    lowValue: 'Parametri vicini alla media indicano squadre simili al livello del campionato.',
    positiveMeaning: 'È utile per produrre una matrice coerente di punteggi e mercati derivati.',
    negativeMeaning: 'Può adattarsi male a cambi strutturali, dati pochi o campionati molto diversi.',
    interpretation: 'Considera versione, finestra di dati e calibrazione quando valuti i risultati.',
    caution: 'Il nome del modello non garantisce qualità: contano implementazione e validazione walk-forward.',
    relatedTerms: ['poisson-distribution', 'lambda', 'backtesting'],
  },
  {
    id: 'negative-binomial',
    term: 'Distribuzione binomiale negativa',
    category: 'Modelli statistici',
    simpleDefinition: 'È un modello per conteggi che ammette più variabilità rispetto alla Poisson.',
    technicalDefinition: 'Aggiunge un parametro di dispersione e permette varianza superiore alla media, utile per tiri, falli o cartellini.',
    example: 'Due squadre con media 12 tiri possono avere frequenze estreme meglio descritte della Poisson.',
    highValue: 'Dispersione alta produce code più larghe e maggiore probabilità di conteggi estremi.',
    lowValue: 'Dispersione bassa avvicina il comportamento alla Poisson.',
    positiveMeaning: 'È utile quando i dati mostrano overdispersione reale e campione sufficiente.',
    negativeMeaning: 'Aggiunge complessità e può diventare instabile con pochi dati.',
    interpretation: 'Confronta media e varianza osservate prima di preferirla alla Poisson.',
    caution: 'Un fit migliore sul passato deve essere confermato fuori campione.',
    relatedTerms: ['poisson-distribution', 'dispersion', 'variance'],
  },
  {
    id: 'variance',
    term: 'Varianza',
    category: 'Modelli statistici',
    simpleDefinition: 'Misura quanto i valori si disperdono rispetto alla loro media.',
    technicalDefinition: 'È la media degli scarti quadratici dalla media e quantifica volatilità di risultati, profitti o metriche.',
    formula: 'Varianza = media((valore − media)²)',
    example: 'Due strategie con stesso ROI possono avere varianza molto diversa tra una scommessa e l’altra.',
    highValue: 'Varianza alta indica risultati più instabili e intervalli di possibile esito più ampi.',
    lowValue: 'Varianza bassa indica maggiore concentrazione attorno alla media.',
    positiveMeaning: 'Conoscerla aiuta a dimensionare campione, stake e aspettative realistiche.',
    negativeMeaning: 'Ignorarla porta a giudicare troppo presto una strategia o a sovradimensionare lo stake.',
    interpretation: 'Non è buona o cattiva da sola: va confrontata con rendimento e tolleranza al rischio.',
    caution: 'Campioni piccoli producono stime di varianza poco affidabili.',
    relatedTerms: ['dispersion', 'statistical-sample', 'roi'],
  },
  {
    id: 'dispersion',
    term: 'Dispersione',
    category: 'Modelli statistici',
    simpleDefinition: 'Descrive quanto i conteggi reali si allontanano dal comportamento medio previsto.',
    technicalDefinition: 'Nel confronto con Poisson, overdispersione significa varianza superiore alla media; underdispersione il contrario.',
    example: 'Cartellini con media 4 ma molti risultati 0 e 9 mostrano forte dispersione.',
    highValue: 'Dispersione alta aumenta probabilità di valori estremi e incertezza sulle linee.',
    lowValue: 'Dispersione bassa concentra i valori attorno alla media.',
    positiveMeaning: 'Stimarla correttamente migliora probabilità Over/Under e intervalli di rischio.',
    negativeMeaning: 'Ignorarla rende le code della distribuzione troppo ottimistiche o pessimistiche.',
    interpretation: 'Usala per scegliere il modello di conteggio appropriato.',
    caution: 'La dispersione osservata può cambiare per competizione, stagione e qualità dei dati.',
    relatedTerms: ['variance', 'negative-binomial'],
  },
  {
    id: 'calibration',
    term: 'Calibrazione',
    category: 'Backtesting e validazione',
    simpleDefinition: 'Misura se probabilità previste e frequenze reali coincidono nel lungo periodo.',
    technicalDefinition: 'Un modello calibrato al 60% dovrebbe vedere l’evento verificarsi circa 60 volte su 100 casi comparabili.',
    example: 'Se gli eventi previsti al 70% accadono solo nel 55% dei casi, il modello è sovraconfidente.',
    highValue: 'Una buona calibrazione significa scarto ridotto tra probabilità previste e frequenze osservate.',
    lowValue: 'Una calibrazione debole segnala probabilità sistematicamente troppo alte o basse.',
    positiveMeaning: 'Rende più credibili EV, edge e sizing derivati dalle probabilità.',
    negativeMeaning: 'Una cattiva calibrazione può generare value apparente e stake eccessivi.',
    interpretation: 'Valutala per fasce di probabilità e su dati fuori campione.',
    caution: 'Precisione di classifica e calibrazione sono proprietà diverse: un modello può eccellere in una sola.',
    relatedTerms: ['model-probability', 'backtesting', 'brier-score'],
  },
  {
    id: 'backtesting',
    term: 'Backtesting',
    category: 'Backtesting e validazione',
    simpleDefinition: 'Simula una strategia su partite storiche per valutarne comportamento e limiti.',
    technicalDefinition: 'Ricostruisce decisioni usando soltanto informazioni disponibili al momento storico, separando addestramento e test.',
    example: 'Si addestra su partite iniziali e si verifica il rendimento sulle partite successive.',
    highValue: 'Molti test coerenti aumentano evidenza, ma non compensano leakage o dati sintetici.',
    lowValue: 'Poche partite producono risultati dominati dalla casualità.',
    positiveMeaning: 'È utile quando usa finestre temporali corrette, quote storiche e metriche multiple.',
    negativeMeaning: 'È ingannevole se riutilizza informazioni future o ottimizza troppo sullo stesso campione.',
    interpretation: 'Leggi ROI insieme a CLV, stabilità, campione e qualità quote.',
    caution: 'Le prestazioni passate non garantiscono quelle future e il mercato può cambiare.',
    relatedTerms: ['walk-forward', 'overfitting', 'historical-snapshot'],
  },
  {
    id: 'walk-forward',
    term: 'Validazione walk-forward',
    aliases: ['walk-forward'],
    category: 'Backtesting e validazione',
    simpleDefinition: 'Testa il modello avanzando nel tempo con finestre successive di addestramento e verifica.',
    technicalDefinition: 'Ogni fold addestra solo su dati precedenti e valuta il periodo seguente, imitando l’uso reale senza guardare il futuro.',
    example: 'Train su agosto-dicembre, test su gennaio; poi la finestra avanza e testa febbraio.',
    highValue: 'Molti fold stabili forniscono evidenza più robusta di un singolo split.',
    lowValue: 'Pochi fold o test molto piccoli rendono la conclusione fragile.',
    positiveMeaning: 'Riduce leakage temporale e mostra come la strategia si comporta in regimi diversi.',
    negativeMeaning: 'Può comunque sovradattarsi se configurazioni e pesi vengono scelti ripetutamente sugli stessi fold.',
    interpretation: 'Confronta risultati tra fold, non soltanto l’aggregato finale.',
    caution: 'Serve abbastanza storia prima del primo test e quote storiche coerenti.',
    relatedTerms: ['training-window', 'test-window', 'fold', 'overfitting'],
  },
  {
    id: 'training-window',
    term: 'Finestra di addestramento',
    aliases: ['training window'],
    category: 'Backtesting e validazione',
    simpleDefinition: 'È l’insieme di partite passate usato per stimare i parametri prima di un test.',
    technicalDefinition: 'Può crescere nel tempo oppure mantenere lunghezza fissa scartando i dati più vecchi.',
    example: 'Le prime 120 partite vengono usate per addestrare prima del primo fold di test.',
    highValue: 'Una finestra ampia riduce rumore ma può includere dati diventati poco rappresentativi.',
    lowValue: 'Una finestra piccola reagisce presto ai cambiamenti ma aumenta instabilità.',
    positiveMeaning: 'È adeguata quando bilancia quantità di dati e rilevanza temporale.',
    negativeMeaning: 'È inadeguata quando troppo corta per il modello o troppo lunga per il regime corrente.',
    interpretation: 'Valuta la dimensione in relazione a competizione, parametri e frequenza di aggiornamento.',
    caution: 'Confrontare esecuzioni con finestre diverse richiede particolare prudenza.',
    relatedTerms: ['expanding-window', 'test-window', 'walk-forward'],
  },
  {
    id: 'test-window',
    term: 'Finestra di test',
    aliases: ['test window'],
    category: 'Backtesting e validazione',
    simpleDefinition: 'È il blocco di partite future rispetto al train su cui il modello viene valutato.',
    technicalDefinition: 'Resta escluso dalla stima dei parametri del fold e misura prestazione fuori campione.',
    example: 'Dopo 120 partite di train, le successive 30 costituiscono la finestra di test.',
    highValue: 'Una finestra ampia stabilizza le metriche ma riduce il numero di fold disponibili.',
    lowValue: 'Una finestra piccola aumenta granularità temporale ma produce metriche più rumorose.',
    positiveMeaning: 'È utile quando rappresenta un periodo operativo realistico e non contamina il train.',
    negativeMeaning: 'È debole se contiene troppo poche decisioni o condizioni non comparabili.',
    interpretation: 'Guarda anche quante scommesse effettive produce, non soltanto quante partite.',
    caution: 'Le partite senza quota reale possono ridurre molto il campione utile.',
    relatedTerms: ['training-window', 'fold', 'statistical-sample'],
  },
  {
    id: 'expanding-window',
    term: 'Finestra crescente',
    aliases: ['expanding window'],
    category: 'Backtesting e validazione',
    simpleDefinition: 'Mantiene tutti i dati storici e aggiunge nuovi incontri a ogni fold.',
    technicalDefinition: 'L’inizio del train resta fisso mentre il termine avanza; si contrappone alla finestra mobile di lunghezza costante.',
    example: 'Train 1 usa 100 partite, train 2 usa le stesse 100 più il primo blocco test.',
    highValue: 'Una storia crescente molto ampia stabilizza i parametri ma può rallentare adattamento.',
    lowValue: 'All’inizio la finestra è più piccola e quindi più sensibile al rumore.',
    positiveMeaning: 'È adatta quando l’intera storia resta rappresentativa del processo.',
    negativeMeaning: 'È meno adatta quando regole, squadre o stili cambiano rapidamente.',
    interpretation: 'Confrontala con una finestra mobile quando sospetti cambi di regime.',
    caution: 'Non confondere crescita del train con utilizzo dei dati futuri: ogni fold resta temporale.',
    relatedTerms: ['training-window', 'walk-forward', 'fold'],
  },
  {
    id: 'fold',
    term: 'Fold',
    category: 'Backtesting e validazione',
    simpleDefinition: 'È una singola coppia temporale di finestra di addestramento e finestra di test.',
    technicalDefinition: 'Produce metriche fuori campione autonome che vengono poi aggregate per misurare stabilità.',
    example: 'Fold 3 addestra fino a marzo e verifica le partite di aprile.',
    highValue: 'Molti fold utili coprono più periodi e consentono di osservare stabilità.',
    lowValue: 'Pochi fold rendono difficile distinguere robustezza da fortuna temporanea.',
    positiveMeaning: 'Un fold positivo contribuisce all’evidenza quando non è isolato dagli altri.',
    negativeMeaning: 'Un fold negativo può rivelare regimi in cui la strategia non funziona.',
    interpretation: 'Osserva dispersione e percentuale di fold positivi oltre alla media.',
    caution: 'Fold sovrapposti non sono completamente indipendenti.',
    relatedTerms: ['walk-forward', 'training-window', 'test-window'],
  },
  {
    id: 'baseline',
    term: 'Baseline',
    category: 'Backtesting e validazione',
    simpleDefinition: 'È un metodo di riferimento semplice usato per capire se il modello attuale aggiunge valore.',
    technicalDefinition: 'Fornisce metriche comparabili con stessi dati e quote, evitando di giudicare l’algoritmo senza un controllo.',
    example: 'Si confronta il ranking corrente con una selezione basata soltanto su edge base.',
    highValue: 'Una baseline forte rende più significativa una superiorità stabile del modello.',
    lowValue: 'Una baseline troppo debole può far apparire buono qualunque algoritmo complesso.',
    positiveMeaning: 'Il modello è promettente quando supera la baseline su più fold e metriche.',
    negativeMeaning: 'Se non la supera, la complessità aggiunta non è giustificata dai risultati.',
    interpretation: 'Confronta ROI, CLV, drawdown e numero di decisioni a condizioni equivalenti.',
    caution: 'Cambiare dataset o filtri tra baseline e modello invalida il confronto.',
    relatedTerms: ['backtesting', 'overfitting', 'walk-forward'],
  },
  {
    id: 'overfitting',
    term: 'Overfitting',
    category: 'Backtesting e validazione',
    simpleDefinition: 'Accade quando il modello impara troppo bene il passato e funziona male su dati nuovi.',
    technicalDefinition: 'Parametri o regole catturano rumore specifico del train invece di relazioni generalizzabili.',
    example: 'Pesi scelti per massimizzare ROI su pochi match crollano nei fold successivi.',
    highValue: 'Rischio alto emerge con molti parametri, pochi dati, tuning ripetuto e forti differenze tra train e test.',
    lowValue: 'Rischio basso richiede semplicità, regolarizzazione e risultati coerenti fuori campione.',
    positiveMeaning: 'Individuare il rischio permette di ridurre complessità o raccogliere più evidenza.',
    negativeMeaning: 'Ignorarlo porta a promuovere strategie che non si ripetono in produzione.',
    interpretation: 'Cerca stabilità tra fold, CLV coerente e prestazioni non concentrate in pochi casi.',
    caution: 'Nessun singolo indicatore elimina completamente il rischio di overfitting.',
    relatedTerms: ['walk-forward', 'baseline', 'statistical-sample'],
  },
  {
    id: 'clv',
    term: 'Closing Line Value (CLV)',
    acronym: 'CLV',
    category: 'Backtesting e validazione',
    simpleDefinition: 'Confronta la quota ottenuta con la quota disponibile vicino alla chiusura del mercato.',
    technicalDefinition: 'Misura se il prezzo preso anticipa favorevolmente il movimento della linea; è un indicatore di qualità decisionale, non dell’esito singolo.',
    formula: 'CLV orientativo = quota presa ÷ quota di chiusura − 1',
    example: 'Quota presa 2,10 e chiusura 2,00 producono CLV positivo di circa 5%.',
    highValue: 'CLV positivo alto indica prezzi mediamente migliori della chiusura.',
    lowValue: 'CLV vicino a zero indica prezzi simili alla chiusura.',
    positiveMeaning: 'CLV positivo suggerisce capacità di anticipare il mercato anche se alcune scommesse perdono.',
    negativeMeaning: 'CLV negativo indica che la quota presa è risultata peggiore di quella finale.',
    interpretation: 'Valutalo su molte scommesse e con snapshot temporali affidabili.',
    caution: 'La formula e il segno possono variare tra sistemi; serve una convenzione coerente.',
    relatedTerms: ['closing-odds', 'historical-snapshot', 'roi'],
  },
  {
    id: 'closing-odds',
    term: 'Quota di chiusura',
    category: 'Backtesting e validazione',
    simpleDefinition: 'È la quota osservata poco prima dell’inizio dell’evento.',
    technicalDefinition: 'Rappresenta il prezzo finale del mercato disponibile per il confronto CLV, purché timestamp e bookmaker siano coerenti.',
    example: 'Una quota registrata cinque minuti prima del kickoff può essere usata come closing line.',
    highValue: 'Una quota di chiusura alta indica che il mercato finale attribuisce probabilità inferiore.',
    lowValue: 'Una quota di chiusura bassa indica aumento della probabilità implicita finale.',
    positiveMeaning: 'È un benchmark utile quando raccolta e orario sono affidabili.',
    negativeMeaning: 'È fuorviante se proviene da un bookmaker o mercato diverso dalla quota iniziale.',
    interpretation: 'Confronta sempre stessa selezione, linea, bookmaker e regole.',
    caution: 'Una rilevazione troppo anticipata non rappresenta una vera quota di chiusura.',
    relatedTerms: ['clv', 'historical-snapshot'],
  },
  {
    id: 'historical-snapshot',
    term: 'Snapshot storico',
    category: 'Fonti e qualità dei dati',
    simpleDefinition: 'È una fotografia delle quote e dei metadati salvata in un preciso momento passato.',
    technicalDefinition: 'Conserva prezzo, fonte, mercato, linea e timestamp necessari a ricostruire una decisione senza usare dati futuri.',
    example: 'Lo snapshot Eurobet delle 14:00 precede il kickoff delle 18:00 e può alimentare il replay.',
    highValue: 'Molti snapshot ben distribuiti migliorano ricostruzione e analisi del movimento quote.',
    lowValue: 'Pochi snapshot lasciano lacune su prezzo disponibile e chiusura.',
    positiveMeaning: 'Rende backtest e replay più realistici e verificabili.',
    negativeMeaning: 'Snapshot incompleti o senza timestamp possono introdurre leakage o confronti falsi.',
    interpretation: 'Verifica sempre fonte, momento, linea e completezza.',
    caution: 'Uno snapshot non dimostra che la quota fosse effettivamente accettabile per qualunque importo.',
    relatedTerms: ['clv', 'closing-odds'],
  },
  {
    id: 'synthetic-odds',
    term: 'Quota sintetica',
    category: 'Fonti e qualità dei dati',
    simpleDefinition: 'È una quota stimata dal modello quando manca un prezzo storico reale.',
    technicalDefinition: 'Viene derivata da probabilità o regole interne per consentire analisi, ma non rappresenta un’offerta eseguibile del bookmaker.',
    example: 'Probabilità modello 50% può essere convertita in quota teorica 2,00.',
    highValue: 'Una quota sintetica alta riflette bassa probabilità stimata, non valore disponibile.',
    lowValue: 'Una quota sintetica bassa riflette alta probabilità stimata.',
    positiveMeaning: 'È utile per diagnostica interna o confronto esplorativo chiaramente etichettato.',
    negativeMeaning: 'È pericolosa se mescolata a quote reali nel ROI o mostrata come quota utente.',
    interpretation: 'Nell’app non deve mai apparire come quota Eurobet o abilitare una puntata.',
    caution: 'Usare la stessa stima per probabilità e quota crea un confronto circolare senza edge reale.',
    relatedTerms: ['model-probability', 'historical-snapshot'],
  },
  {
    id: 'data-quality',
    term: 'Qualità dei dati',
    category: 'Fonti e qualità dei dati',
    simpleDefinition: 'Riassume completezza, freschezza, coerenza e affidabilità dei dati usati.',
    technicalDefinition: 'Considera valori mancanti, copertura temporale, fonte, matching delle entità e anomalie che possono alterare il modello.',
    example: 'Dati xG completi ma arbitro assente producono qualità diversa per mercati gol e cartellini.',
    highValue: 'Qualità alta indica copertura sufficiente, fonte coerente e aggiornamento recente.',
    lowValue: 'Qualità bassa indica lacune, ritardi o matching incerto.',
    positiveMeaning: 'Supporta stime e spiegazioni più credibili.',
    negativeMeaning: 'Può rendere fragile un edge anche numericamente elevato.',
    interpretation: 'Valutala per il mercato specifico: non esiste una qualità unica per tutta la partita.',
    caution: 'Completezza non equivale a correttezza; servono anche controlli di plausibilità.',
    relatedTerms: ['statistical-sample', 'confidence'],
  },
  {
    id: 'statistical-sample',
    term: 'Campione statistico',
    category: 'Fonti e qualità dei dati',
    simpleDefinition: 'È il numero e la varietà delle osservazioni usate per calcolare una metrica.',
    technicalDefinition: 'Dimensione, indipendenza e rappresentatività determinano quanto una stima può generalizzare oltre i dati osservati.',
    example: 'ROI +30% su 5 scommesse è molto meno informativo di +6% su 500 scommesse coerenti.',
    highValue: 'Un campione ampio riduce rumore casuale, purché resti rappresentativo.',
    lowValue: 'Un campione piccolo produce intervalli ampi e risultati instabili.',
    positiveMeaning: 'È positivo quando copre periodi e condizioni diverse senza mescolare fenomeni incompatibili.',
    negativeMeaning: 'È negativo quando selezionato dopo aver visto i risultati o dominato da pochi casi.',
    interpretation: 'Mostra sempre il numero di partite o scommesse accanto alle metriche aggregate.',
    caution: 'Più dati non aiutano se sono obsoleti, duplicati o provenienti da un processo diverso.',
    relatedTerms: ['variance', 'roi', 'overfitting'],
  },
  {
    id: 'brier-score',
    term: 'Brier score',
    category: 'Backtesting e validazione',
    simpleDefinition: 'Misura quanto le probabilità previste sono vicine agli esiti realmente osservati.',
    technicalDefinition: 'È la media dell’errore quadratico tra probabilità prevista ed esito binario, quindi premia stime accurate e ben calibrate.',
    formula: 'Brier = media((probabilità prevista − esito reale)²)',
    example: 'Prevedere 70% e osservare un esito positivo produce errore (0,70 − 1)² = 0,09.',
    highValue: 'Un valore alto indica probabilità complessivamente meno accurate.',
    lowValue: 'Un valore basso è migliore e indica previsioni più vicine agli esiti.',
    positiveMeaning: 'È positivo quando migliora rispetto a una baseline valutata sullo stesso campione.',
    negativeMeaning: 'È negativo quando peggiora o viene confrontato su campioni diversi.',
    interpretation: 'Leggilo insieme a calibrazione, log loss e numerosità del campione.',
    caution: 'Il valore dipende dal problema e dalla frequenza degli eventi: non esiste una soglia universale.',
    relatedTerms: ['calibration', 'log-loss', 'baseline', 'statistical-sample'],
  },
  {
    id: 'log-loss',
    term: 'Log loss',
    category: 'Backtesting e validazione',
    simpleDefinition: 'Valuta la qualità delle probabilità penalizzando molto le previsioni sicure che risultano sbagliate.',
    technicalDefinition: 'È la perdita logaritmica negativa assegnata alla probabilità dell’esito osservato; è una proper scoring rule.',
    formula: 'Log loss = −media(y·ln(p) + (1−y)·ln(1−p))',
    example: 'Assegnare 99% a un evento che non accade genera una penalità molto maggiore rispetto a stimare 60%.',
    highValue: 'Un valore alto è peggiore e segnala probabilità inaccurate o eccessivamente sicure.',
    lowValue: 'Un valore basso è migliore e indica buona assegnazione di probabilità agli esiti.',
    positiveMeaning: 'È positivo quando scende rispetto alla baseline sullo stesso test.',
    negativeMeaning: 'È negativo quando cresce o viene migliorato soltanto sui dati di addestramento.',
    interpretation: 'Confronta versioni del modello sullo stesso walk-forward, non valori isolati.',
    caution: 'Probabilità pari a zero o uno richiedono limiti numerici e rendono gli errori estremamente costosi.',
    relatedTerms: ['brier-score', 'calibration', 'walk-forward', 'overfitting'],
  },
  {
    id: 'yield',
    term: 'Yield',
    category: 'Backtesting e validazione',
    simpleDefinition: 'Esprime il profitto netto in rapporto al totale degli importi puntati.',
    technicalDefinition: 'Nel backtesting è normalmente profitto netto diviso turnover delle puntate, moltiplicato per cento.',
    formula: 'Yield (%) = profitto netto / totale puntato × 100',
    example: 'Con 1.000 € puntati complessivamente e 50 € di profitto, lo yield è 5%.',
    highValue: 'Un valore alto è favorevole, ma può essere instabile su poche scommesse.',
    lowValue: 'Un valore vicino a zero indica pareggio; sotto zero indica perdita.',
    positiveMeaning: 'È positivo quando il profitto netto supera zero su un campione credibile.',
    negativeMeaning: 'È negativo quando i ritorni sono inferiori al capitale complessivamente puntato.',
    interpretation: 'Valutalo con numero di giocate, drawdown, quote medie e intervallo temporale.',
    caution: 'Può coincidere con alcune definizioni di ROI: verifica sempre il denominatore usato dal report.',
    relatedTerms: ['roi', 'drawdown', 'statistical-sample'],
  },
  {
    id: 'drawdown',
    term: 'Drawdown',
    category: 'Gestione del bankroll',
    simpleDefinition: 'È la perdita dal precedente massimo del bankroll fino al minimo successivo.',
    technicalDefinition: 'Il maximum drawdown misura il peggior calo peak-to-trough nella curva cumulata del capitale.',
    formula: 'Drawdown = (valore corrente − massimo precedente) / massimo precedente',
    example: 'Un bankroll che sale a 1.200 € e poi scende a 900 € registra un drawdown del 25%.',
    highValue: 'Un drawdown alto indica una flessione severa e maggiore pressione sul capitale.',
    lowValue: 'Un drawdown basso indica una curva più stabile, a parità di rendimento.',
    positiveMeaning: 'È positivo quando resta sostenibile rispetto al bankroll e ai limiti di rischio.',
    negativeMeaning: 'È negativo quando può portare a esaurimento del capitale o abbandono della strategia.',
    interpretation: 'Confrontalo con ROI, stake, esposizione e durata del periodo negativo.',
    caution: 'Lo storico osservato non garantisce che il drawdown futuro non possa essere peggiore.',
    relatedTerms: ['bankroll', 'stake', 'exposure', 'roi'],
  },
];

const entriesWithPlainLanguage = entries.map((entry) => {
  const plainLanguageCopy = GLOSSARY_PLAIN_LANGUAGE[entry.id];
  if (!plainLanguageCopy) {
    throw new Error(`Manca la spiegazione semplice per il termine del glossario: ${entry.id}`);
  }
  return { ...entry, ...plainLanguageCopy };
});

export const GLOSSARY_ENTRIES = [...entriesWithPlainLanguage].sort((left, right) =>
  left.term.localeCompare(right.term, 'it', { sensitivity: 'base' })
);

export const GLOSSARY_BY_ID = new Map(GLOSSARY_ENTRIES.map((entry) => [entry.id, entry]));

export const getGlossaryEntry = (id: string | null | undefined): GlossaryEntry | null =>
  id ? GLOSSARY_BY_ID.get(id) ?? null : null;
