import type { GlossaryEntry } from './glossaryTypes';

export type PlainLanguageGlossaryCopy = Pick<
  GlossaryEntry,
  'simpleDefinition' | 'technicalDefinition' | 'example' | 'interpretation' | 'caution'
>;

export const GLOSSARY_PLAIN_LANGUAGE: Record<string, PlainLanguageGlossaryCopy> = {
  'decimal-odds': {
    simpleDefinition: 'In parole povere: indica quanto ricevi in totale se punti 1 € e vinci. La somma comprende anche l’euro che avevi puntato.',
    technicalDefinition: 'Serve a trasformare una puntata in una possibile restituzione. Più la quota è alta, più la vincita potenziale cresce, ma l’esito è di solito considerato meno probabile.',
    example: 'Punti 10 € a quota 2,10: se vinci ricevi 21 € in tutto. Il guadagno vero è 11 €, perché 10 € erano già tuoi.',
    interpretation: 'Per te significa che la quota mostra quanto puoi ricevere, non quanto è sicura la giocata.',
    caution: 'Una quota alta non è automaticamente conveniente e una quota bassa non rende certa la vittoria.',
  },
  'implied-probability': {
    simpleDefinition: 'In parole povere: traduce una quota nella possibilità che il bookmaker assegna a un risultato.',
    technicalDefinition: 'Si ricava dalla quota e serve per capire come il mercato sta valutando l’esito. Dentro questa stima è normalmente compreso anche il margine del bookmaker.',
    example: 'Quota 2,00 significa circa 50 possibilità su 100; quota 1,50 significa circa 67 possibilità su 100.',
    interpretation: 'Per te è il punto di partenza da confrontare con la stima dell’app.',
    caution: 'Non è la probabilità vera e definitiva: comprende il margine del bookmaker e può cambiare nel tempo.',
  },
  'model-probability': {
    simpleDefinition: 'In parole povere: è la migliore stima dell’app su quanto è probabile un risultato. Non è una promessa.',
    technicalDefinition: 'L’app la calcola usando partite passate, statistiche e informazioni disponibili. Va letta come stima su molti casi simili, non come certezza sulla singola partita.',
    example: 'Se l’app indica 60%, vuol dire che in 100 situazioni davvero simili ci si aspetterebbero circa 60 successi, non che questa giocata vincerà di sicuro.',
    interpretation: 'Per te significa: più la percentuale è alta, più l’esito è ritenuto possibile, ma può comunque perdere.',
    caution: 'Dati mancanti, pochi precedenti o cambi dell’ultimo momento possono rendere la stima meno affidabile.',
  },
  vig: {
    simpleDefinition: 'In parole povere: è il guadagno che il bookmaker inserisce nelle quote, un po’ come un costo nascosto nel prezzo.',
    technicalDefinition: 'Il bookmaker abbassa leggermente le quote rispetto a un mercato perfettamente equo. Questa differenza rende più difficile ottenere un guadagno nel lungo periodo.',
    example: 'Se tutti gli esiti di una partita, trasformati in percentuali, arrivano al 105%, quel 5% in più rappresenta circa il margine del bookmaker.',
    interpretation: 'Per te significa che la quota offerta è normalmente un po’ meno favorevole del prezzo teoricamente giusto.',
    caution: 'Il margine non dice quale squadra è più forte: indica soltanto quanto il prezzo è sfavorevole al cliente.',
  },
  overround: {
    simpleDefinition: 'In parole povere: è la parte che supera il 100% quando si sommano le possibilità indicate dalle quote di tutti gli esiti.',
    technicalDefinition: 'Serve a stimare quanto margine è stato inserito dal bookmaker in un mercato completo, per esempio vittoria in casa, pareggio e vittoria fuori.',
    example: 'Casa 48%, pareggio 30% e ospite 28% fanno 106%. I 6 punti oltre il 100% sono l’overround.',
    interpretation: 'Per te significa che, in generale, un valore più basso corrisponde a prezzi meno penalizzanti.',
    caution: 'Non misura il guadagno certo del bookmaker e va calcolato usando tutti gli esiti dello stesso mercato.',
  },
  'no-vig-odds': {
    simpleDefinition: 'In parole povere: è una quota teorica ottenuta togliendo il margine del bookmaker.',
    technicalDefinition: 'Serve come prezzo di confronto più neutrale. È calcolata dall’app e non è necessariamente una quota che puoi davvero giocare.',
    example: 'Se la quota reale è 1,90 ma, tolto il margine, il prezzo equo sarebbe 2,00, la seconda è una quota teorica di confronto.',
    interpretation: 'Per te aiuta a capire come il mercato valuterebbe l’esito senza il proprio costo incorporato.',
    caution: 'Non confonderla con una vera offerta: per scommettere conta soltanto la quota reale indicata dal bookmaker.',
  },
  'value-bet': {
    simpleDefinition: 'In parole povere: è una giocata il cui possibile premio sembra abbastanza alto rispetto al rischio stimato dall’app.',
    technicalDefinition: 'C’è valore teorico quando la quota paga più di quanto dovrebbe secondo la probabilità stimata. Il concetto riguarda molte giocate simili, non il risultato immediato.',
    example: 'L’app stima un esito al 55% e trova quota 2,00. Su molti casi simili, quel prezzo potrebbe essere favorevole.',
    interpretation: 'Per te significa che il prezzo può essere interessante, non che la giocata sia più probabile o sicura.',
    caution: 'Anche una buona value bet può perdere. Se la stima dell’app è sbagliata, il valore può essere solo apparente.',
  },
  'expected-value': {
    simpleDefinition: 'In parole povere: indica quanto potresti guadagnare o perdere in media ripetendo tante volte giocate simili.',
    technicalDefinition: 'Confronta il premio della quota con la possibilità stimata di vincere. Un valore positivo suggerisce convenienza teorica nel lungo periodo.',
    example: 'EV +10% non significa guadagnare subito 10 €. Significa che, su tante puntate da 10 € simili, la media teorica sarebbe circa +1 € per puntata.',
    interpretation: 'Per te è un indicatore di convenienza nel lungo periodo, non una previsione del risultato di stasera.',
    caution: 'Un EV molto alto può dipendere da una quota anomala o da una stima poco affidabile: va sempre controllato.',
  },
  edge: {
    simpleDefinition: 'In parole povere: è quanto la stima dell’app differisce da quella del mercato.',
    technicalDefinition: 'Misura la distanza tra la probabilità calcolata dall’app e quella ricavata dalle quote, preferibilmente dopo aver tolto il margine del bookmaker.',
    example: 'L’app stima 56% e il mercato 51%: la differenza, cioè l’edge, è di 5 punti percentuali.',
    interpretation: 'Per te un edge positivo segnala una possibile occasione da valutare con quota, dati e affidabilità.',
    caution: 'Una differenza piccola può essere semplice errore di stima e può sparire se la quota cambia.',
  },
  bankroll: {
    simpleDefinition: 'In parole povere: è il denaro che hai deciso di riservare soltanto alle scommesse.',
    technicalDefinition: 'È il budget separato usato per calcolare le puntate e controllare il rischio, senza coinvolgere soldi necessari per affitto, bollette o altre spese.',
    example: 'Se separi 500 € per le scommesse, il tuo bankroll è 500 €. Una puntata dell’1% vale 5 €.',
    interpretation: 'Per te è il limite economico entro cui muoverti e da cui calcolare ogni puntata.',
    caution: 'Non usare denaro necessario alla vita quotidiana e non aumentare il bankroll per inseguire una perdita.',
  },
  stake: {
    simpleDefinition: 'In parole povere: è la quantità di denaro che metti su una singola scommessa.',
    technicalDefinition: 'Può essere indicato in euro oppure come percentuale del bankroll. Stabilisce quanto puoi perdere e quanto puoi ricevere su quella giocata.',
    example: 'Con un bankroll di 800 €, uno stake dell’1,5% corrisponde a una puntata di 12 €.',
    interpretation: 'Per te lo stake suggerito è un limite prudente, non un obbligo a puntare quella cifra.',
    caution: 'Non aumentarlo per recuperare in fretta: una puntata più grande aumenta anche la perdita possibile.',
  },
  exposure: {
    simpleDefinition: 'In parole povere: è la somma del denaro attualmente impegnato in scommesse non ancora concluse.',
    technicalDefinition: 'Mostra quanta parte del bankroll è ancora a rischio mentre aspetti i risultati. Aiuta a evitare troppe puntate aperte nello stesso momento.',
    example: 'Hai tre giocate ancora aperte da 10 €, 15 € e 20 €: la tua esposizione totale è 45 €.',
    interpretation: 'Per te indica quanto denaro potresti perdere se le scommesse aperte andassero male insieme.',
    caution: 'Due puntate sulla stessa partita possono essere collegate: la semplice somma non mostra sempre tutto il rischio.',
  },
  'kelly-criterion': {
    simpleDefinition: 'In parole povere: è una formula che propone quanto puntare in base al vantaggio stimato e alla quota.',
    technicalDefinition: 'Cerca di far crescere il bankroll nel lungo periodo, ma funziona bene soltanto se la probabilità inserita è abbastanza corretta.',
    example: 'Con quota 2,00 e probabilità stimata al 55%, il Kelly completo suggerirebbe il 10% del bankroll, una cifra molto aggressiva.',
    interpretation: 'Per te è un riferimento matematico per dimensionare la puntata, non un comando da seguire alla lettera.',
    caution: 'Il Kelly completo può suggerire puntate troppo grandi se l’app sopravvaluta anche di poco la probabilità.',
  },
  'fractional-kelly': {
    simpleDefinition: 'In parole povere: usa solo una parte della puntata proposta dal metodo Kelly, per rischiare meno.',
    technicalDefinition: 'Riduce la puntata matematica completa scegliendo, per esempio, metà o un quarto. La crescita possibile diminuisce, ma anche gli sbalzi del bankroll.',
    example: 'Se Kelly completo suggerisce l’8%, un Kelly a un quarto propone il 2% del bankroll.',
    interpretation: 'Per te è una versione più prudente che protegge meglio dagli errori della stima.',
    caution: 'Ridurre la puntata limita il rischio, ma non trasforma una valutazione sbagliata in una buona giocata.',
  },
  roi: {
    simpleDefinition: 'In parole povere: mostra quanto hai guadagnato o perso rispetto a tutti i soldi che hai puntato.',
    technicalDefinition: 'Confronta il risultato netto con il totale delle puntate concluse. Permette di confrontare periodi diversi, ma va letto insieme al numero di giocate.',
    example: 'Hai puntato in totale 1.000 € e, dopo aver recuperato le puntate, ti restano 80 € di guadagno: il ROI è +8%.',
    interpretation: 'Per te un ROI positivo indica guadagno, uno negativo perdita; più giocate ci sono, più il dato è utile.',
    caution: 'Un ROI molto alto ottenuto con poche scommesse può dipendere dalla fortuna e non durare nel tempo.',
  },
  'win-rate': {
    simpleDefinition: 'In parole povere: è la percentuale delle scommesse concluse che hai vinto.',
    technicalDefinition: 'Conta le vittorie rispetto a vittorie e sconfitte. Da solo non dice se hai guadagnato, perché non considera quanto pagavano le quote.',
    example: 'Vinci 58 scommesse e ne perdi 42: il tuo tasso di vittoria è 58%. Potresti comunque essere in perdita se le quote erano troppo basse.',
    interpretation: 'Per te dice quanto spesso vinci, ma deve essere letto insieme a quote, profitto e numero di giocate.',
    caution: 'Vincere spesso non basta: dieci piccole vincite possono essere cancellate da una perdita molto grande.',
  },
  'pending-bet': {
    simpleDefinition: 'In parole povere: è una scommessa ancora aperta perché la partita o il controllo del risultato non è terminato.',
    technicalDefinition: 'La puntata è stata registrata, ma non è ancora classificata come vinta, persa o annullata. Per questo non entra nei risultati definitivi.',
    example: 'Hai giocato Roma–Napoli che inizia stasera: fino al risultato finale la scommessa resta in attesa.',
    interpretation: 'Per te significa che quel denaro è ancora impegnato e il profitto non è ancora noto.',
    caution: 'Non contare una scommessa in attesa come guadagno o perdita prima della sua chiusura ufficiale.',
  },
  void: {
    simpleDefinition: 'In parole povere: indica una scommessa annullata, di solito con restituzione della puntata.',
    technicalDefinition: 'La giocata non viene considerata né vinta né persa. Il bookmaker applica le proprie regole per decidere quando annullarla.',
    example: 'Una partita viene rinviata oltre il limite previsto: il bookmaker annulla la giocata e restituisce i 10 € puntati.',
    interpretation: 'Per te significa che, normalmente, non c’è né guadagno né perdita su quella puntata.',
    caution: 'Le regole cambiano tra bookmaker e mercati: controlla sempre le condizioni dell’operatore usato.',
  },
  confidence: {
    simpleDefinition: 'In parole povere: indica quanto l’app considera solida la propria valutazione, non la possibilità certa di vincere.',
    technicalDefinition: 'Riassume elementi come quantità dei dati, stabilità del modello e chiarezza del vantaggio. È diversa dalla probabilità dell’esito.',
    example: 'Una giocata può avere probabilità 65% ma confidenza media se mancano dati recenti o la quota sta cambiando molto.',
    interpretation: 'Per te una confidenza alta significa dati e segnali più solidi, non risultato garantito.',
    caution: 'Non leggere “alta confidenza” come “scommessa sicura”: nello sport restano sempre risultati inattesi.',
  },
  speculative: {
    simpleDefinition: 'In parole povere: segnala un’idea rischiosa, basata su dati o vantaggi troppo deboli per essere una vera raccomandazione.',
    technicalDefinition: 'L’app usa questa etichetta quando la valutazione può essere interessante da osservare, ma non supera tutti i controlli richiesti per una giocata consigliata.',
    example: 'La quota sembra buona, ma ci sono pochi dati sul giocatore: l’app può segnare la proposta come speculativa.',
    interpretation: 'Per te significa “informazione da osservare”, non “puntata consigliata”.',
    caution: 'Le proposte speculative sono più incerte: non trattarle come scorciatoie per trovare quote alte.',
  },
  'european-handicap': {
    simpleDefinition: 'In parole povere: aggiunge o toglie gol virtuali prima della partita, ma lascia possibili tre risultati: casa, pareggio o ospite.',
    technicalDefinition: 'Il risultato reale viene corretto con il vantaggio indicato e poi valutato come un normale mercato a tre esiti.',
    example: 'Napoli parte con −1: se vince 2-0, dopo il gol virtuale tolto il risultato diventa 1-0 e la giocata Napoli vince.',
    interpretation: 'Per te conta il risultato dopo aver applicato il vantaggio o lo svantaggio scritto nella linea.',
    caution: 'Non confonderlo con l’handicap asiatico: qui il pareggio corretto può essere un esito perdente separato.',
  },
  'asian-handicap': {
    simpleDefinition: 'In parole povere: dà un vantaggio virtuale a una squadra e può eliminare il pareggio o restituire tutta o parte della puntata.',
    technicalDefinition: 'La linea scelta cambia il modo in cui la scommessa viene chiusa. Alcune linee possono produrre vincita o perdita a metà.',
    example: 'Giochi Inter 0: se vince, vinci; se pareggia, ricevi indietro la puntata; se perde, perdi.',
    interpretation: 'Per te bisogna leggere con attenzione il numero della linea, perché cambia il risultato della giocata.',
    caution: 'Linee come −0,25 o +0,75 dividono la puntata in due parti e sono facili da interpretare male.',
  },
  lambda: {
    simpleDefinition: 'In parole povere: è il numero medio di gol che il modello si aspetta da una squadra in quella partita.',
    technicalDefinition: 'È un valore usato nei calcoli dei punteggi possibili. Può avere decimali perché rappresenta una media, non un risultato esatto.',
    example: 'Lambda 1,6 non significa che la squadra segnerà 1,6 gol: significa una media attesa tra molte partite simili.',
    interpretation: 'Per te un valore più alto indica maggiore produzione di gol prevista.',
    caution: 'È una media: non esclude affatto che la squadra segni zero gol o ne segni tre.',
  },
  'poisson-distribution': {
    simpleDefinition: 'In parole povere: è un metodo che calcola la possibilità di vedere 0, 1, 2, 3 o più gol partendo dalla media attesa.',
    technicalDefinition: 'Trasforma il numero medio di eventi previsti in probabilità per ogni quantità possibile. Nel calcio viene spesso usato per gol e punteggi.',
    example: 'Se una squadra ha una media attesa di 1,5 gol, il metodo stima separatamente quanto sono possibili 0, 1, 2, 3 gol e così via.',
    interpretation: 'Per te serve a passare da una media generica alle probabilità dei diversi risultati.',
    caution: 'È una semplificazione: espulsioni, infortuni e andamento della partita possono rendere i gol meno regolari.',
  },
  'dixon-coles': {
    simpleDefinition: 'In parole povere: è una correzione del calcolo dei gol pensata per rendere più realistici i punteggi bassi nel calcio.',
    technicalDefinition: 'Modifica soprattutto le probabilità di risultati come 0-0, 1-0, 0-1 e 1-1, che un calcolo più semplice può valutare male.',
    example: 'Se il metodo base sottovaluta gli 0-0, Dixon-Coles corregge quella parte usando ciò che è successo nelle partite reali.',
    interpretation: 'Per te significa una stima dei punteggi bassi un po’ più adatta al calcio.',
    caution: 'Migliora un limite specifico, ma non può prevedere eventi imprevedibili della singola partita.',
  },
  'negative-binomial': {
    simpleDefinition: 'In parole povere: è un metodo per contare eventi quando i risultati cambiano più del previsto, per esempio tanti o pochissimi tiri.',
    technicalDefinition: 'Viene usato quando una semplice media non descrive bene gli sbalzi osservati. Permette quindi una maggiore varietà di risultati possibili.',
    example: 'Due squadre possono avere media 10 tiri, ma passare spesso da 4 a 18: questo metodo rappresenta meglio tali differenze.',
    interpretation: 'Per te indica che il modello sta tenendo conto di risultati molto variabili.',
    caution: 'Un metodo più flessibile non compensa dati scarsi, sbagliati o non rappresentativi.',
  },
  variance: {
    simpleDefinition: 'In parole povere: misura quanto i risultati tendono ad allontanarsi dalla loro media.',
    technicalDefinition: 'Un valore alto indica risultati molto diversi tra loro; un valore basso indica risultati più vicini e regolari.',
    example: 'Due squadre fanno in media 10 tiri: una resta quasi sempre tra 9 e 11, l’altra passa da 3 a 17. La seconda ha più variabilità.',
    interpretation: 'Per te più variabilità significa più sorprese e risultati meno prevedibili nel breve periodo.',
    caution: 'Non indica se un risultato è buono o cattivo: descrive soltanto quanto cambia.',
  },
  dispersion: {
    simpleDefinition: 'In parole povere: confronta quanto cambiano davvero i risultati con quanto il modello si aspettava che cambiassero.',
    technicalDefinition: 'Serve a capire se un modello produce risultati troppo concentrati o troppo sparsi rispetto ai dati osservati nelle partite.',
    example: 'Il modello prevede quasi sempre 8-12 tiri, ma i dati reali vanno spesso da 3 a 18: la dispersione reale è maggiore.',
    interpretation: 'Per te segnala se il modello sta rappresentando bene gli alti e bassi dei dati.',
    caution: 'Va valutata su molte partite: pochi risultati estremi possono dare un’impressione sbagliata.',
  },
  calibration: {
    simpleDefinition: 'In parole povere: controlla se le percentuali date dall’app si verificano davvero con una frequenza simile.',
    technicalDefinition: 'Un modello è ben calibrato quando, tra tutte le previsioni segnate al 60%, l’esito si verifica circa 60 volte ogni 100.',
    example: 'Se 100 pronostici indicati al 70% vincono soltanto 50 volte, il modello sta mostrando troppa sicurezza.',
    interpretation: 'Per te una buona calibrazione rende le percentuali più credibili e più facili da confrontare con le quote.',
    caution: 'Una buona calibrazione non garantisce guadagno: servono anche quote favorevoli e un numero sufficiente di casi.',
  },
  backtesting: {
    simpleDefinition: 'In parole povere: prova una strategia sulle partite passate per vedere come si sarebbe comportata.',
    technicalDefinition: 'Il test deve usare, per ogni data, soltanto le informazioni che sarebbero state disponibili allora, così da non barare conoscendo già il futuro.',
    example: 'Si applicano le regole alle partite della stagione scorsa e si calcolano vittorie, perdite e rendimento come se si fosse giocato allora.',
    interpretation: 'Per te è una prova storica utile per scartare idee deboli, non una garanzia sui risultati futuri.',
    caution: 'Un test può sembrare ottimo se usa dati futuri, quote inventate o regole scelte apposta dopo aver visto i risultati.',
  },
  'walk-forward': {
    simpleDefinition: 'In parole povere: il modello studia il passato, viene provato sul periodo subito dopo e poi avanza ripetendo il processo.',
    technicalDefinition: 'Questo metodo imita l’uso reale nel tempo: in ogni passaggio il futuro resta nascosto durante la preparazione del modello.',
    example: 'Studia agosto-dicembre, prova gennaio; poi studia fino a gennaio e prova febbraio, continuando mese dopo mese.',
    interpretation: 'Per te è un controllo più realistico di un test che mescola liberamente partite vecchie e nuove.',
    caution: 'Resta una simulazione: qualità delle quote, dati mancanti e cambi del campionato possono influire sui risultati.',
  },
  'training-window': {
    simpleDefinition: 'In parole povere: è il periodo di partite passate che il modello usa per imparare.',
    technicalDefinition: 'Contiene i dati disponibili prima del periodo di prova. La sua lunghezza decide quanta storia viene considerata.',
    example: 'Per prevedere gennaio, il modello può studiare tutte le partite giocate da agosto a dicembre.',
    interpretation: 'Per te una finestra più lunga offre più dati, mentre una più corta segue meglio i cambiamenti recenti.',
    caution: 'Troppa storia può includere squadre ormai cambiate; troppo poca può rendere la stima instabile.',
  },
  'test-window': {
    simpleDefinition: 'In parole povere: è il periodo successivo usato per verificare se ciò che il modello ha imparato funziona davvero.',
    technicalDefinition: 'Le partite di questo periodo non devono essere usate durante l’apprendimento. Servono soltanto a misurare la qualità delle previsioni.',
    example: 'Il modello studia agosto-dicembre e viene giudicato sulle partite di gennaio, che non aveva visto prima.',
    interpretation: 'Per te mostra come il modello si comporta su casi nuovi, più vicini all’uso reale.',
    caution: 'Se le partite di prova entrano per errore nei dati di apprendimento, il risultato appare migliore di quanto sia davvero.',
  },
  'expanding-window': {
    simpleDefinition: 'In parole povere: il periodo usato per imparare diventa sempre più grande man mano che arrivano nuove partite.',
    technicalDefinition: 'La data iniziale resta fissa, mentre la data finale avanza. Così il modello conserva la storia e aggiunge progressivamente nuovi dati.',
    example: 'Prima studia agosto-dicembre, poi agosto-gennaio, poi agosto-febbraio e così via.',
    interpretation: 'Per te significa che il modello impara da sempre più partite senza usare quelle ancora future.',
    caution: 'Può dare troppo peso a dati molto vecchi se squadre, allenatori o competizioni sono cambiati molto.',
  },
  fold: {
    simpleDefinition: 'In parole povere: è uno dei singoli giri di prova in cui il modello studia un periodo e viene controllato su quello successivo.',
    technicalDefinition: 'Più giri permettono di vedere se i risultati restano buoni in momenti diversi invece di dipendere da un solo periodo fortunato.',
    example: 'Un giro usa agosto-dicembre per imparare e gennaio per provare; il giro dopo usa i dati fino a gennaio e prova febbraio.',
    interpretation: 'Per te ogni giro è un controllo separato della stabilità del modello nel tempo.',
    caution: 'Un solo giro positivo non basta: bisogna guardare se il comportamento si ripete negli altri periodi.',
  },
  baseline: {
    simpleDefinition: 'In parole povere: è un metodo semplice usato come termine di paragone per capire se il modello complesso migliora davvero qualcosa.',
    technicalDefinition: 'Può essere una media storica o una regola elementare. Un nuovo modello è utile soltanto se supera questo riferimento in modo stabile.',
    example: 'Prima si prova “usa sempre la media gol del campionato”; poi si controlla se il modello avanzato fa davvero meglio.',
    interpretation: 'Per te è l’asticella minima che una soluzione più complicata dovrebbe superare.',
    caution: 'Se il modello non batte il riferimento semplice su dati nuovi, la complessità aggiunta probabilmente non serve.',
  },
  overfitting: {
    simpleDefinition: 'In parole povere: succede quando il modello impara troppo bene i dettagli casuali del passato e poi sbaglia sui casi nuovi.',
    technicalDefinition: 'Il modello sembra eccellente sulle partite già viste, ma non ha imparato regole generali capaci di funzionare in futuro.',
    example: 'Una regola perfetta per la stagione scorsa crolla appena cambia stagione: probabilmente aveva imparato coincidenze, non segnali solidi.',
    interpretation: 'Per te è un falso miglioramento: bello nei risultati storici, debole quando serve davvero.',
    caution: 'Aggiungere più regole e dettagli può peggiorare il problema, soprattutto quando le partite disponibili sono poche.',
  },
  clv: {
    simpleDefinition: 'In parole povere: confronta la quota presa da te con quella disponibile poco prima dell’inizio della partita.',
    technicalDefinition: 'Serve a capire se hai ottenuto un prezzo migliore o peggiore rispetto al prezzo finale del mercato, senza aspettare il risultato della giocata.',
    example: 'Giochi a quota 2,10 e prima del calcio d’inizio la stessa selezione scende a 1,90: hai ottenuto un prezzo migliore.',
    interpretation: 'Per te ottenere spesso quote migliori di quelle finali può indicare buone decisioni di prezzo.',
    caution: 'Un buon confronto con la quota finale non garantisce che la singola scommessa vinca né prova da solo un profitto futuro.',
  },
  'closing-odds': {
    simpleDefinition: 'In parole povere: è la quota disponibile vicino all’inizio della partita, quando il mercato ha raccolto quasi tutte le informazioni.',
    technicalDefinition: 'Viene usata come riferimento finale per confrontare il prezzo ottenuto prima. Può comunque cambiare tra bookmaker e pochi istanti diversi.',
    example: 'Hai giocato lunedì a quota 2,05; sabato, poco prima della partita, la quota dello stesso mercato è 1,92.',
    interpretation: 'Per te è un prezzo di confronto utile per valutare quando hai piazzato la scommessa.',
    caution: 'Devi confrontare lo stesso bookmaker, mercato, linea e momento; altrimenti il confronto può essere scorretto.',
  },
  'historical-snapshot': {
    simpleDefinition: 'In parole povere: è una fotografia delle quote salvata in un momento preciso del passato.',
    technicalDefinition: 'Conserva prezzo, fonte e orario così che un test storico possa usare soltanto ciò che era davvero disponibile in quel momento.',
    example: 'Lo snapshot delle 15:00 registra Milan vincente a 2,20; alle 18:00 un altro snapshot può registrare 2,05.',
    interpretation: 'Per te permette di sapere quale quota si poteva realmente trovare a una certa ora.',
    caution: 'Uno snapshot mancante o preso dopo l’evento non può dimostrare quale prezzo fosse giocabile prima della partita.',
  },
  'synthetic-odds': {
    simpleDefinition: 'In parole povere: è una quota inventata dal modello per fare calcoli interni, non un prezzo offerto da un vero bookmaker.',
    technicalDefinition: 'Può riempire un dato mancante durante analisi tecniche, ma non rappresenta denaro realmente giocabile e non deve essere usata per dimostrare profitto.',
    example: 'Se manca la quota Over 2.5, il sistema può stimare 1,95 per un controllo interno: nessun bookmaker ha però offerto davvero quel prezzo.',
    interpretation: 'Per te significa “dato teorico”: non è una quota sulla quale puoi piazzare una scommessa.',
    caution: 'Non va mostrata come quota reale né usata per dichiarare un guadagno ottenibile.',
  },
  'data-quality': {
    simpleDefinition: 'In parole povere: indica se i dati usati dall’app sono completi, corretti, recenti e coerenti.',
    technicalDefinition: 'Controlla problemi come valori mancanti, squadre abbinate male, statistiche vecchie o informazioni provenienti da una fonte non adatta.',
    example: 'Se mancano i tiri delle ultime cinque partite, la qualità dei dati per una previsione sui tiri è bassa.',
    interpretation: 'Per te dati migliori rendono la stima più credibile; dati deboli richiedono più prudenza.',
    caution: 'Un modello sofisticato non può correggere automaticamente informazioni mancanti o sbagliate.',
  },
  'statistical-sample': {
    simpleDefinition: 'In parole povere: è il numero e la varietà dei casi usati per calcolare o controllare un risultato.',
    technicalDefinition: 'Un insieme ampio e rappresentativo riduce il peso della fortuna. Non conta solo la quantità: i casi devono anche assomigliare a quelli che vuoi prevedere.',
    example: 'Un rendimento positivo su 12 giocate dice poco; lo stesso risultato su 1.000 giocate diverse è molto più informativo.',
    interpretation: 'Per te più casi utili significano in genere maggiore fiducia nel risultato osservato.',
    caution: 'Migliaia di dati vecchi o tutti molto simili possono essere meno utili di un insieme più piccolo ma adatto.',
  },
  'brier-score': {
    simpleDefinition: 'In parole povere: è un voto dato alle percentuali previste dall’app. Più è basso, meglio è.',
    technicalDefinition: 'Confronta ogni probabilità dichiarata con ciò che è successo davvero e penalizza la distanza tra previsione e risultato.',
    example: 'Dire 90% su un evento che non accade viene penalizzato molto più che dire 55% sullo stesso evento.',
    interpretation: 'Per te un valore più basso indica percentuali mediamente più vicine ai risultati reali.',
    caution: 'Ha senso soltanto confrontando gli stessi mercati e periodi; un numero isolato è difficile da giudicare.',
  },
  'log-loss': {
    simpleDefinition: 'In parole povere: è un voto che punisce molto le previsioni sicurissime quando risultano sbagliate. Più è basso, meglio è.',
    technicalDefinition: 'Valuta la qualità delle percentuali dando un costo particolarmente alto agli errori fatti con eccessiva sicurezza.',
    example: 'Prevedere 99% e sbagliare pesa molto più che prevedere 60% e sbagliare, perché nel primo caso il modello era quasi certo.',
    interpretation: 'Per te aiuta a capire se l’app evita di mostrarsi troppo sicura quando non dovrebbe.',
    caution: 'Va confrontato sullo stesso tipo di previsione e sullo stesso insieme di partite.',
  },
  yield: {
    simpleDefinition: 'In parole povere: mostra il guadagno o la perdita netta come percentuale di tutto il denaro puntato.',
    technicalDefinition: 'Divide il risultato netto per il totale delle puntate concluse. In molti report è molto simile, o identico, al ROI delle scommesse.',
    example: 'Punti complessivamente 2.000 € e guadagni 100 € netti: il rendimento sulle puntate è +5%.',
    interpretation: 'Per te indica quanto hanno reso, in media, gli euro messi in gioco.',
    caution: 'Controlla sempre come viene calcolato: alcuni report usano parole diverse per la stessa misura.',
  },
  drawdown: {
    simpleDefinition: 'In parole povere: è quanto il bankroll è sceso rispetto al suo precedente punto più alto.',
    technicalDefinition: 'Misura il peggior calo osservato dal massimo raggiunto al minimo successivo. Aiuta a capire quanto può essere difficile sopportare un periodo negativo.',
    example: 'Il bankroll sale a 1.200 € e poi scende a 900 €: il calo dal massimo è 300 €, cioè il 25%.',
    interpretation: 'Per te mostra la perdita temporanea più pesante vissuta dal budget durante il periodo osservato.',
    caution: 'Il peggior calo futuro può essere maggiore di quello visto finora: lo storico non fissa un limite sicuro.',
  },
};
